### ISSUE TITLE
В каком случае задачу нужно перезапускать, а в каком нет?

### ISSUE THREAD

**Issue by kenenbek** [skygrid/grid_simulation#8]
Согласно этой картинке есть задачи, которые перезапускаются и есть которые просто считаются failed. 
И чем отличаются done задачи от completed?
![c08bfd63232094e39a68bdc952ead918](https://cloud.githubusercontent.com/assets/15985969/17062687/a0752eba-503c-11e6-88e3-8a3caf15af64.png)

**Comment by hushchyn-mikhail** [comment]
Из файла с описанием: "When the Agent fails to submit a job to the local batch system, the job is automatically rescheduled and can be picked up by another production site."

Если задача падает по другим причинам, она не перезапускается.
