### ISSUE TITLE
Output data только у user данных?

### ISSUE THREAD

**Issue by kenenbek** [skygrid/grid_simulation#9]
Согласно этой картинке, за последние полгода все 100% аутпут данных только у юзеров. Так должно быть?
![outputdata_by_jobtype](https://cloud.githubusercontent.com/assets/15985969/17086909/76195ecc-5206-11e6-88da-b03c4884dfd2.png)

В то время как input дата были распределены таким образом:
![input_by_type](https://cloud.githubusercontent.com/assets/15985969/17086914/9a80e456-5206-11e6-97c4-b3fa8c8e0086.png)

**Comment by hushchyn-mikhail** [comment]
Да, такое может быть. Но 0% у DataStripping на первой картинке смотрится странно. Возможно, это особенности построения картинки.
